global using AdventOfCSharp;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Text.RegularExpressions;
global using Garyon.DataStructures;
global using Garyon.Extensions;
global using Garyon.Extensions.ArrayExtensions;
